In [73]:
import pandas as pd
import geopandas as gpd
import io
import requests
import os

In [74]:
cwd = os.getcwd()

In [75]:
start_date = '2020-03-01' 
end_date = '2020-03-20'

In [76]:
device_list = [10, 16, 36]  #list of devices considered to make the request

In [77]:
aq_data = []

In [78]:
for i in range(len(device_list)):
    url = 'https://api.aqp.eo.esa.int/api/device/'+str(device_list[i])+'/csv?start_date='+start_date+'&end_date='+end_date
    urlData = requests.get(url).content
    rawData = pd.read_csv(io.StringIO(urlData.decode('utf-8')))
    aq_data.append(rawData)

df_data = pd.concat((pd.DataFrame(data) for data in aq_data), ignore_index=True)

In [79]:
df_data

,id,device_id,acquisition_date,latitude,longitude,gps_precision,pm25,pm10,humidity,temperature,...,nh3,co,created_at,updated_at,sensor1,sensor2,sensor3,sensor4,sensor5,timestamp
0,3563250,10,2020-03-04 12:55:47,45.793356,9.432461,0,0.0,0.0,35.9,23.0,...,0.45,7.80,2020-03-04 11:55:49,2020-03-04 11:55:49,10.0,10.0,10.0,"CO=7.79496847319ppm ,NH3=0.454364346641ppm ,NO...",add info,1583322947
1,3563264,10,2020-03-04 12:56:54,45.793356,9.432461,0,0.0,0.0,35.7,23.0,...,0.46,7.80,2020-03-04 11:56:57,2020-03-04 11:56:57,10.0,10.0,10.0,"CO=7.79496847319ppm ,NH3=0.461148005064ppm ,NO...",add info,1583323014
2,3563280,10,2020-03-04 12:58:02,45.793356,9.432461,0,0.0,0.0,35.5,22.9,...,0.45,7.80,2020-03-04 11:58:04,2020-03-04 11:58:04,10.0,10.0,10.0,"CO=7.79496847319ppm ,NH3=0.454364346641ppm ,NO...",add info,1583323082
3,3563295,10,2020-03-04 12:59:10,45.793356,9.432461,0,0.0,0.0,35.4,22.9,...,0.44,7.80,2020-03-04 11:59:12,2020-03-04 11:59:12,10.0,10.0,10.0,"CO=7.79496847319ppm ,NH3=0.440977146912ppm ,NO...",add info,1583323150
4,3563311,10,2020-03-04 13:00:17,45.793356,9.432461,0,0.0,0.0,35.4,22.9,...,0.43,7.80,2020-03-04 12:00:19,2020-03-04 12:00:19,10.0,10.0,10.0,"CO=7.79496847319ppm ,NH3=0.434373038583ppm ,NO...",add info,1583323217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62499,3842943,36,2020-03-19 13:36:28,45.476914,10.412889,0,14.7,26.6,18.4,21.2,...,0.67,3.78,2020-03-19 13:36:31,2020-03-19 13:36:31,10.0,10.0,10.0,"CO=3.78297567113ppm ,NH3=0.668134306112ppm ,NO...",add info,1584621388
62500,3842956,36,2020-03-19 13:37:34,45.476914,10.412889,0,15.1,20.6,18.1,21.2,...,0.67,3.78,2020-03-19 13:37:36,2020-03-19 13:37:36,10.0,10.0,10.0,"CO=3.78297567113ppm ,NH3=0.668134306112ppm ,NO...",add info,1584621454
62501,3842971,36,2020-03-19 13:38:39,45.476914,10.412889,0,15.7,23.0,17.9,21.2,...,0.67,3.78,2020-03-19 13:38:42,2020-03-19 13:38:42,10.0,10.0,10.0,"CO=3.78297567113ppm ,NH3=0.668134306112ppm ,NO...",add info,1584621519
62502,3842986,36,2020-03-19 13:39:44,45.476914,10.412889,0,15.3,20.6,17.8,21.2,...,0.67,3.78,2020-03-19 13:39:47,2020-03-19 13:39:47,10.0,10.0,10.0,"CO=3.78297567113ppm ,NH3=0.668134306112ppm ,NO...",add info,1584621584
62503,3881860,36,2020-03-19 13:18:11,45.476914,10.412889,0,25.4,33.3,35.0,18.0,...,0.67,3.78,2020-03-21 15:51:02,2020-03-21 15:51:02,10.0,10.0,10.0,"CO=3.78297567113ppm ,NH3=0.668134306112ppm ,NO...",add info,1584620291

In [80]:
sel_columns = ['device_id', 'acquisition_date','latitude', 
           'longitude', 'pm25', 'pm10', 'humidity', 'temperature',
          'no2', 'co2', 'nh3', 'co']

In [81]:
df_data.device_id.unique()

array([10, 16, 36], dtype=int64)

In [82]:
aq_data = df_data[sel_columns]

In [83]:
aq_data['acquisition_date'] = pd.to_datetime(aq_data['acquisition_date'], format='%Y-%m-%d %H:%M:%S')

C:\Users\Administrator\AppData\Local\Temp\ipykernel_17672\513061078.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aq_data['acquisition_date'] = pd.to_datetime(aq_data['acquisition_date'], format='%Y-%m-%d %H:%M:%S')

In [84]:
aq_means = aq_data.groupby(['device_id'], as_index=False).mean()
aq_means

,device_id,latitude,longitude,pm25,pm10,humidity,temperature,no2,co2,nh3,co
0,10,45.794067,9.432082,0.000000,0.000000,39.896907,21.397458,0.660148,1802.440763,0.491081,10.418476
1,16,45.477748,9.227293,0.694999,1.004039,63.722861,15.217118,0.189870,382.265807,0.605391,3.896322
2,36,45.528947,10.258868,2.955477,6.075616,11.160726,21.768176,0.159816,263.142648,292.319776,22.032321

In [88]:
pm25 = aq_means[['device_id', 'latitude', 'longitude', 'pm25']].rename(columns={"pm25": "value"})
pm10 = aq_means[['device_id', 'latitude', 'longitude', 'pm10']].rename(columns={"pm10": "value"})
hum = aq_means[['device_id', 'latitude', 'longitude', 'humidity']].rename(columns={"humidity": "value"})
temp = aq_means[['device_id', 'latitude', 'longitude', 'temperature']].rename(columns={"temperature": "value"})
no2 = aq_means[['device_id', 'latitude', 'longitude', 'no2']].rename(columns={"no2": "value"})
co2 = aq_means[['device_id', 'latitude', 'longitude', 'co2']].rename(columns={"co2": "value"})
nh3 = aq_means[['device_id', 'latitude', 'longitude', 'nh3']].rename(columns={"nh3": "value"})
co = aq_means[['device_id', 'latitude', 'longitude', 'co']].rename(columns={"co": "value"})

In [89]:
pm25_gdf = gpd.GeoDataFrame(pm25, geometry=gpd.points_from_xy(pm25.longitude, pm25.latitude)).set_crs('epsg:4326')
pm10_gdf = gpd.GeoDataFrame(pm10, geometry=gpd.points_from_xy(pm10.longitude, pm10.latitude)).set_crs('epsg:4326')
hum_gdf = gpd.GeoDataFrame(hum, geometry=gpd.points_from_xy(hum.longitude, hum.latitude)).set_crs('epsg:4326')
temp_gdf = gpd.GeoDataFrame(temp, geometry=gpd.points_from_xy(temp.longitude, temp.latitude)).set_crs('epsg:4326')
no2_gdf = gpd.GeoDataFrame(no2, geometry=gpd.points_from_xy(no2.longitude, no2.latitude)).set_crs('epsg:4326')
co2_gdf = gpd.GeoDataFrame(co2, geometry=gpd.points_from_xy(co2.longitude, co2.latitude)).set_crs('epsg:4326')
nh3_gdf = gpd.GeoDataFrame(nh3, geometry=gpd.points_from_xy(nh3.longitude, nh3.latitude)).set_crs('epsg:4326')
co_gdf = gpd.GeoDataFrame(co, geometry=gpd.points_from_xy(nh3.longitude, nh3.latitude)).set_crs('epsg:4326')

In [90]:
pm25_gdf.to_file(cwd+"/temp/pm25_lcs.gpkg", driver="GPKG")
pm10_gdf.to_file(cwd+"/temp/pm10_lcs.gpkg", driver="GPKG")
hum_gdf.to_file(cwd+"/temp/hum_lcs.gpkg", driver="GPKG")
temp_gdf.to_file(cwd+"/temp/temp_lcs.gpkg", driver="GPKG")
no2_gdf.to_file(cwd+"/temp/no2_lcs.gpkg", driver="GPKG")
co2_gdf.to_file(cwd+"/temp/co2_lcs.gpkg", driver="GPKG")
nh3_gdf.to_file(cwd+"/temp/amm_lcs.gpkg", driver="GPKG")
co_gdf.to_file(cwd+"/temp/co_lcs.gpkg", driver="GPKG")

C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,
C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,
C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,
C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,
C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,
C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,
C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,
C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,

In [32]:
# for i in range(100):
#     url ='https://api.aqp.eo.esa.int/api/device/'+str(i)
#     print(requests.get(url).content)

b'{\n    "message": "Server Error"\n}'
b'{"data":{"id":1,"uuid":"aaaa","name":"Lorem","affiliation":"TBD (ID 1)"}}'
b'{"data":{"id":2,"uuid":"bbbb","name":"lorem","affiliation":"ESERO Austria (ID 2)"}}'
b'{"data":{"id":3,"uuid":"cccc","name":"","affiliation":"Polish Space Agency (POLSA) (ID 3)"}}'
b'{"data":{"id":4,"uuid":"dddd","name":"","affiliation":"ESRIN (Demo unit #1) (ID 4)"}}'
b'{"data":{"id":5,"uuid":"eeee","name":"","affiliation":"Universit\\u00e0 di Pavia (ID 5)"}}'
b'{"data":{"id":6,"uuid":"6","name":"","affiliation":"Liceo Scientifico Statale Leonardo da Vinci (ID 6)"}}'
b'{"data":{"id":7,"uuid":"7","name":"","affiliation":"Liceo scientifico e linguistico Marconi di Milano (ID 7)"}}'
b'{"data":{"id":8,"uuid":"8","name":"","affiliation":"Liceo Scientifico Einstein di Milano (ID 8)"}}'
b'{"data":{"id":9,"uuid":"9","name":"","affiliation":"ITT E.Molinari di Milano (ID 9)"}}'
b'{"data":{"id":10,"uuid":"10","name":"","affiliation":"Istituto Superiore Lorenzo Rota (ID 10)"}}'
b'{"data":{"id":11,"uuid":"11","name":"","affiliation":"IIS JC Maxwell (ID 11)"}}'
b'{"data":{"id":12,"uuid":"12","name":"","affiliation":"ISIS Paolo Carcano (ID 12)"}}'
b'{"data":{"id":13,"uuid":"13","name":"","affiliation":"IIS Curie Sraffa di Milano (ID 13)"}}'
b'{"data":{"id":14,"uuid":"14","name":"","affiliation":"Swiss school (ID 14)"}}'
b'{"data":{"id":15,"uuid":"15","name":"","affiliation":"Politecnico di Milano (ID 15)"}}'
b'{"data":{"id":16,"uuid":"16","name":"","affiliation":"Politecnico di Milano (ID 16)"}}'
b'{"data":{"id":17,"uuid":"17","name":"","affiliation":"Politecnico di Milano (ID 17)"}}'
b'{"data":{"id":18,"uuid":"18","name":"","affiliation":"Politecnico di Milano (ID 18)"}}'
b'{"data":{"id":19,"uuid":"19","name":"","affiliation":"Politecnico di Milano (ID 19)"}}'
b'{"data":{"id":20,"uuid":"20","name":"","affiliation":"ESRIN (Reference Platform) (ID 20)"}}'
b'{"data":{"id":21,"uuid":"21","name":"","affiliation":"ESRIN (Demo unit #2) (ID 21)"}}'
b'{"data":{"id":22,"uuid":"22","name":"","affiliation":"Liceo Volterra Ciampino (ID 22)"}}'
b'{"data":{"id":23,"uuid":"23","name":"","affiliation":"ESERO Romania (ID 23)"}}'
b'{"data":{"id":24,"uuid":"24","name":"","affiliation":"ESERO Italy (ID 24)"}}'
b'{"data":{"id":25,"uuid":"25","name":"","affiliation":"ESERO Belgium (ID 25)"}}'
b'{"data":{"id":26,"uuid":"26","name":"","affiliation":"ESERO Czech Republic (ID 26)"}}'
b'{"data":{"id":27,"uuid":"27","name":"","affiliation":"ESERO Denmark (ID 27)"}}'
b'{"data":{"id":28,"uuid":"28","name":"","affiliation":"ESERO Portugal (ID 28)"}}'
b'{"data":{"id":29,"uuid":"29","name":"","affiliation":"ESERO Spain (ID 29)"}}'
b'{"data":{"id":30,"uuid":"30","name":"","affiliation":"ESERO UK (ID 30)"}}'
b'{"data":{"id":31,"uuid":"31","name":"","affiliation":"ESERO-ESTEC (ID 31)"}}'
b'{"data":{"id":32,"uuid":"32","name":"","affiliation":"ESRIN (Test Platform) (ID 32)"}}'
b'{"data":{"id":33,"uuid":"33","name":"","affiliation":"Universitat Polit\\u00e8cnica de Catalunya (UPC) (ID 33)"}}'
b'{"data":{"id":34,"uuid":"34","name":"","affiliation":"ID 34"}}'
b'{"data":{"id":35,"uuid":"35","name":"","affiliation":"ID 35"}}'
b'{"data":{"id":36,"uuid":"36","name":"","affiliation":"ID 36"}}'
b'{"data":{"id":37,"uuid":"37","name":"","affiliation":"ID 37"}}'
b'{"data":{"id":38,"uuid":"38","name":"","affiliation":"ID 38"}}'
b'{"data":{"id":39,"uuid":"39","name":"","affiliation":"ID 39"}}'
b'{"data":{"id":40,"uuid":"40","name":"","affiliation":"ID 40"}}'
b'{"data":{"id":41,"uuid":"41","name":"","affiliation":"ID 41"}}'
b'{"data":{"id":42,"uuid":"42","name":"","affiliation":"ID 42"}}'
b'{"data":{"id":43,"uuid":"43","name":"","affiliation":"ID 43"}}'
b'{"data":{"id":44,"uuid":"44","name":"","affiliation":"ID 44"}}'
b'{"data":{"id":45,"uuid":"45","name":"","affiliation":"ID 45"}}'
b'{"data":{"id":46,"uuid":"46","name":"","affiliation":"Rocca Priora1 (ID 46)"}}'
b'{"data":{"id":47,"uuid":"47","name":"","affiliation":"Outdoor modern ver (ID 47)"}}'
b'{"data":{"id":48,"uuid":"48","name":"","affiliation":"Louis XVI (ID 48)"}}'
b'{"data":{"id":49,"uuid":"49","name":"","affiliation":"ID 49"}}'
b'{"data":{"id":50,"uuid":"50","name":"","affiliation":"DARWIN CAV (ID 50)"}}'
b'{"data":{"id":51,"uuid":"aqp-51","name":"","affiliation":"Gedaservice1 (ID 51)"}}'
b'{"data":{"id":52,"uuid":"aqp-52","name":"","affiliation":"ID 52"}}'
b'{"data":{"id":53,"uuid":"aqp-53","name":"","affiliation":"ID 53"}}'
b'{"data":{"id":54,"uuid":"aqp-54","name":"","affiliation":"Gedaservice SG (ID 54)"}}'
b'{"data":{"id":55,"uuid":"aqp-55","name":"","affiliation":"Elena Mignini (ID 55)"}}'
b'{"data":{"id":56,"uuid":"aqp-56","name":"","affiliation":"ECoistituto RE-GE (ID 56)"}}'
b'{"data":{"id":57,"uuid":"aqp-57","name":"","affiliation":"Paulo Sacramento (ID 57)"}}'
b'{"data":{"id":58,"uuid":"aqp-58","name":"","affiliation":"Gedaservice Test1 (ID 58)"}}'
b'{"data":{"id":59,"uuid":"aqp-59","name":"","affiliation":"Gedaservice Test2 (ID 59)"}}'
b'{"data":{"id":60,"uuid":"aqp-60","name":"","affiliation":"ID 60"}}'
b'{"data":{"id":61,"uuid":"aqp-61","name":"","affiliation":"ID 61"}}'
b'{"data":{"id":62,"uuid":"aqp-62","name":"","affiliation":"ID 62"}}'
b'{"data":{"id":63,"uuid":"aqp-63","name":"","affiliation":"ID 63"}}'
b'{"data":{"id":64,"uuid":"aqp-64","name":"","affiliation":"ID 64"}}'
b'{"data":{"id":65,"uuid":"aqp-65","name":"","affiliation":"ID 65"}}'
b'{"data":{"id":66,"uuid":"aqp-66","name":"","affiliation":"ID 66"}}'
b'{"data":{"id":67,"uuid":"aqp-67","name":"","affiliation":"ID 67"}}'
b'{"data":{"id":68,"uuid":"aqp-68","name":"","affiliation":"ID 68"}}'
b'{"data":{"id":69,"uuid":"aqp-69","name":"","affiliation":"ID 69"}}'
b'{"data":{"id":70,"uuid":"aqp-70","name":"","affiliation":"ID 70"}}'
b'{"data":{"id":71,"uuid":"aqp-71","name":"","affiliation":"ID 71"}}'
b'{"data":{"id":72,"uuid":"aqp-72","name":"","affiliation":"ID 72"}}'
b'{"data":{"id":73,"uuid":"aqp-73","name":"","affiliation":"ID 73"}}'
b'{"data":{"id":74,"uuid":"aqp-74","name":"","affiliation":"ID 74"}}'
b'{"data":{"id":75,"uuid":"aqp-75","name":"","affiliation":"ID 75"}}'
b'{"data":{"id":76,"uuid":"aqp-76","name":"","affiliation":"ID 76"}}'
b'{"data":{"id":77,"uuid":"aqp-77","name":"","affiliation":"ID 77"}}'
b'{"data":{"id":78,"uuid":"aqp-78","name":"","affiliation":"ID 78"}}'
b'{"data":{"id":79,"uuid":"aqp-79","name":"","affiliation":"ID 79"}}'
b'{"data":{"id":80,"uuid":"aqp-80","name":"","affiliation":"ID 80"}}'
b'{"data":{"id":81,"uuid":"aqp-81","name":"","affiliation":"ID 81"}}'
b'{"data":{"id":82,"uuid":"aqp-82","name":"","affiliation":"ID 82"}}'
b'{"data":{"id":83,"uuid":"aqp-83","name":"","affiliation":"ID 83"}}'
b'{"data":{"id":84,"uuid":"aqp-84","name":"","affiliation":"ID 84"}}'
b'{"data":{"id":85,"uuid":"aqp-85","name":"","affiliation":"ID 85"}}'
b'{"data":{"id":86,"uuid":"aqp-86","name":"","affiliation":"ID 86"}}'
b'{"data":{"id":87,"uuid":"aqp-87","name":"","affiliation":"ID 87"}}'
b'{"data":{"id":88,"uuid":"aqp-88","name":"","affiliation":"ID 88"}}'
b'{"data":{"id":89,"uuid":"aqp-89","name":"","affiliation":"ID 89"}}'
b'{"data":{"id":90,"uuid":"aqp-90","name":"","affiliation":"ID 90"}}'
b'{"data":{"id":91,"uuid":"aqp-91","name":"","affiliation":"ID 91"}}'
b'{"data":{"id":92,"uuid":"aqp-92","name":"","affiliation":"ID 92"}}'
b'{"data":{"id":93,"uuid":"aqp-93","name":"","affiliation":"ID 93"}}'
b'{"data":{"id":94,"uuid":"aqp-94","name":"","affiliation":"ID 94"}}'
b'{"data":{"id":95,"uuid":"aqp-95","name":"","affiliation":"ID 95"}}'
b'{"data":{"id":96,"uuid":"aqp-96","name":"","affiliation":"ID 96"}}'
b'{"data":{"id":97,"uuid":"aqp-97","name":"","affiliation":"ID 97"}}'
b'{"data":{"id":98,"uuid":"aqp-98","name":"","affiliation":"ID 98"}}'
b'{"data":{"id":99,"uuid":"aqp-99","name":"","affiliation":"ID 99"}}'

In [ ]:
lc_id = [10, 16, 36] #station in Lombardy region