In [1]:
import pandas as pd
import geopandas as gpd
import io
import requests
import os

In [2]:
cwd = os.getcwd()

Modify **date.json** file to change the date:

In [3]:
d = open('date.json')
date = json.load(d)
start_date = date["start_date"]
end_date = date["end_date"]

In [4]:
device_list = [10, 16, 36]  #list of devices considered to make the request

In [5]:
aq_data = []

In [6]:
for i in range(len(device_list)):
    url = 'https://api.aqp.eo.esa.int/api/device/'+str(device_list[i])+'/csv?start_date='+start_date+'&end_date='+end_date
    urlData = requests.get(url).content
    rawData = pd.read_csv(io.StringIO(urlData.decode('utf-8')))
    aq_data.append(rawData)

df_data = pd.concat((pd.DataFrame(data) for data in aq_data), ignore_index=True)

In [7]:
df_data

,id,device_id,acquisition_date,latitude,longitude,gps_precision,pm25,pm10,humidity,temperature,...,nh3,co,created_at,updated_at,sensor1,sensor2,sensor3,sensor4,sensor5,timestamp
0,3032040,10,2020-02-01 00:00:40,45.793435,9.432191,0,0.0,0.0,49.4,21.4,...,0.59,8.08,2020-01-31 23:00:42,2020-01-31 23:00:42,10.0,10.0,10.0,"CO=8.08336876754ppm ,NH3=0.59387350011ppm ,NO2...",add info,1580511640
1,3032052,10,2020-02-01 00:01:47,45.793435,9.432191,0,0.0,0.0,49.4,21.4,...,0.59,8.08,2020-01-31 23:01:50,2020-01-31 23:01:50,10.0,10.0,10.0,"CO=8.08336876754ppm ,NH3=0.59387350011ppm ,NO2...",add info,1580511707
2,3032064,10,2020-02-01 00:02:55,45.793435,9.432191,0,0.0,0.0,49.3,21.3,...,0.59,8.08,2020-01-31 23:02:57,2020-01-31 23:02:57,10.0,10.0,10.0,"CO=8.08336876754ppm ,NH3=0.585956407819ppm ,NO...",add info,1580511775
3,3032076,10,2020-02-01 00:04:06,45.793435,9.432191,0,0.0,0.0,49.4,21.4,...,0.59,8.08,2020-01-31 23:04:08,2020-01-31 23:04:08,10.0,10.0,10.0,"CO=8.08336876754ppm ,NH3=0.59387350011ppm ,NO2...",add info,1580511846
4,3032089,10,2020-02-01 00:05:13,45.793435,9.432191,0,0.0,0.0,49.3,21.3,...,0.59,8.08,2020-01-31 23:05:15,2020-01-31 23:05:15,10.0,10.0,10.0,"CO=8.08336876754ppm ,NH3=0.59387350011ppm ,NO2...",add info,1580511913
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74361,3476371,36,2020-02-28 13:31:03,45.534717,10.231533,1,7.9,11.9,1.0,24.7,...,0.67,3.78,2020-02-28 12:31:09,2020-02-28 12:31:09,10.0,10.0,10.0,"CO=3.78297567113ppm ,NH3=0.668134306112ppm ,NO...",add info,1582893063
74362,3476387,36,2020-02-28 13:32:18,45.534755,10.231545,1,7.4,7.8,1.0,24.5,...,0.67,3.78,2020-02-28 12:32:22,2020-02-28 12:32:22,10.0,10.0,10.0,"CO=3.78297567113ppm ,NH3=0.668134306112ppm ,NO...",add info,1582893138
74363,3476404,36,2020-02-28 13:33:34,45.534797,10.231520,1,7.5,8.0,1.0,24.3,...,0.67,3.78,2020-02-28 12:33:39,2020-02-28 12:33:39,10.0,10.0,10.0,"CO=3.78297567113ppm ,NH3=0.668134306112ppm ,NO...",add info,1582893214
74364,3476421,36,2020-02-28 13:34:53,45.534791,10.231480,1,8.9,22.4,1.0,24.3,...,0.67,3.78,2020-02-28 12:35:02,2020-02-28 12:35:02,10.0,10.0,10.0,"CO=3.78297567113ppm ,NH3=0.668134306112ppm ,NO...",add info,1582893293
74365,3522718,36,2020-02-28 13:17:28,45.534791,10.231480,0,4.3,7.6,17.9,16.1,...,0.67,3.78,2020-03-02 08:11:41,2020-03-02 08:11:41,10.0,10.0,10.0,"CO=3.78297567113ppm ,NH3=0.668134306112ppm ,NO...",add info,1582892248

In [8]:
sel_columns = ['device_id', 'acquisition_date','latitude', 
           'longitude', 'pm25', 'pm10', 'humidity', 'temperature',
          'no2', 'co2', 'nh3', 'co']

In [9]:
df_data.device_id.unique()

array([10, 16, 36], dtype=int64)

In [10]:
aq_data = df_data[sel_columns]

In [11]:
aq_data['acquisition_date'] = pd.to_datetime(aq_data['acquisition_date'], format='%Y-%m-%d %H:%M:%S')

C:\Users\Administrator\AppData\Local\Temp\ipykernel_24144\513061078.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aq_data['acquisition_date'] = pd.to_datetime(aq_data['acquisition_date'], format='%Y-%m-%d %H:%M:%S')

In [12]:
aq_means = aq_data.groupby(['device_id'], as_index=False).mean()
aq_means

,device_id,latitude,longitude,pm25,pm10,humidity,temperature,no2,co2,nh3,co
0,10,45.795012,9.432206,0.000015,0.000026,39.273452,22.834320,0.755277,2471.263984,0.495912,10.304848
1,16,45.477748,9.227293,1.413951,2.288366,56.501576,14.288167,0.173952,423.615419,0.635811,3.900457
2,36,45.506699,10.243984,7.174843,10.247646,8.059556,22.424584,0.115183,330.573687,0.670048,3.781829

In [13]:
pm25 = aq_means[['device_id', 'latitude', 'longitude', 'pm25']].rename(columns={"pm25": "value"})
pm10 = aq_means[['device_id', 'latitude', 'longitude', 'pm10']].rename(columns={"pm10": "value"})
hum = aq_means[['device_id', 'latitude', 'longitude', 'humidity']].rename(columns={"humidity": "value"})
temp = aq_means[['device_id', 'latitude', 'longitude', 'temperature']].rename(columns={"temperature": "value"})
no2 = aq_means[['device_id', 'latitude', 'longitude', 'no2']].rename(columns={"no2": "value"})
co2 = aq_means[['device_id', 'latitude', 'longitude', 'co2']].rename(columns={"co2": "value"})
nh3 = aq_means[['device_id', 'latitude', 'longitude', 'nh3']].rename(columns={"nh3": "value"})
co = aq_means[['device_id', 'latitude', 'longitude', 'co']].rename(columns={"co": "value"})

In [14]:
pm25_gdf = gpd.GeoDataFrame(pm25, geometry=gpd.points_from_xy(pm25.longitude, pm25.latitude)).set_crs('epsg:4326')
pm10_gdf = gpd.GeoDataFrame(pm10, geometry=gpd.points_from_xy(pm10.longitude, pm10.latitude)).set_crs('epsg:4326')
hum_gdf = gpd.GeoDataFrame(hum, geometry=gpd.points_from_xy(hum.longitude, hum.latitude)).set_crs('epsg:4326')
temp_gdf = gpd.GeoDataFrame(temp, geometry=gpd.points_from_xy(temp.longitude, temp.latitude)).set_crs('epsg:4326')
no2_gdf = gpd.GeoDataFrame(no2, geometry=gpd.points_from_xy(no2.longitude, no2.latitude)).set_crs('epsg:4326')
co2_gdf = gpd.GeoDataFrame(co2, geometry=gpd.points_from_xy(co2.longitude, co2.latitude)).set_crs('epsg:4326')
nh3_gdf = gpd.GeoDataFrame(nh3, geometry=gpd.points_from_xy(nh3.longitude, nh3.latitude)).set_crs('epsg:4326')
co_gdf = gpd.GeoDataFrame(co, geometry=gpd.points_from_xy(co.longitude, co.latitude)).set_crs('epsg:4326')

In [15]:
pm25_gdf.to_file(cwd+"/temp/pm25_lcs.gpkg", driver="GPKG")
pm10_gdf.to_file(cwd+"/temp/pm10_lcs.gpkg", driver="GPKG")
hum_gdf.to_file(cwd+"/temp/hum_lcs.gpkg", driver="GPKG")
temp_gdf.to_file(cwd+"/temp/temp_lcs.gpkg", driver="GPKG")
no2_gdf.to_file(cwd+"/temp/no2_lcs.gpkg", driver="GPKG")
co2_gdf.to_file(cwd+"/temp/co2_lcs.gpkg", driver="GPKG")
nh3_gdf.to_file(cwd+"/temp/amm_lcs.gpkg", driver="GPKG")
co_gdf.to_file(cwd+"/temp/co_lcs.gpkg", driver="GPKG")

C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,
C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,
C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,
C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,
C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,
C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,
C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,
C:\Users\Administrator\anaconda3\envs\ddust\lib\site-packages\geopandas\io\file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,

In [16]:
# for i in range(100):
#     url ='https://api.aqp.eo.esa.int/api/device/'+str(i)
#     print(requests.get(url).content)

In [17]:
lc_id = [10, 16, 36] #station in Lombardy region